// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package models

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TodoPriority.
const (
	TodoPriorityHigh   TodoPriority = "high"
	TodoPriorityLow    TodoPriority = "low"
	TodoPriorityMedium TodoPriority = "medium"
)

// Defines values for TodoCreatePriority.
const (
	TodoCreatePriorityHigh   TodoCreatePriority = "high"
	TodoCreatePriorityLow    TodoCreatePriority = "low"
	TodoCreatePriorityMedium TodoCreatePriority = "medium"
)

// Defines values for TodoUpdatePriority.
const (
	TodoUpdatePriorityHigh   TodoUpdatePriority = "high"
	TodoUpdatePriorityLow    TodoUpdatePriority = "low"
	TodoUpdatePriorityMedium TodoUpdatePriority = "medium"
)

// Defines values for GetTodosParamsPriority.
const (
	GetTodosParamsPriorityHigh   GetTodosParamsPriority = "high"
	GetTodosParamsPriorityLow    GetTodosParamsPriority = "low"
	GetTodosParamsPriorityMedium GetTodosParamsPriority = "medium"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// Todo defines model for Todo.
type Todo struct {
	// Completed Whether the todo is completed.
	Completed bool `json:"completed"`

	// CreatedAt The timestamp when the todo was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Description Detailed description of the todo.
	Description *string `json:"description,omitempty"`

	// DueDate The due date for the todo.
	DueDate *time.Time `json:"due_date,omitempty"`

	// Id The unique identifier for the todo.
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Priority Priority level of the todo.
	Priority *TodoPriority `json:"priority,omitempty"`

	// Title The title of the todo.
	Title string `json:"title"`

	// UpdatedAt The timestamp when the todo was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// TodoPriority Priority level of the todo.
type TodoPriority string

// TodoCreate defines model for TodoCreate.
type TodoCreate struct {
	// Description Detailed description of the todo.
	Description *string `json:"description,omitempty"`

	// DueDate The due date for the todo.
	DueDate *time.Time `json:"due_date,omitempty"`

	// Priority Priority level of the todo.
	Priority *TodoCreatePriority `json:"priority,omitempty"`

	// Title The title of the todo.
	Title string `json:"title"`
}

// TodoCreatePriority Priority level of the todo.
type TodoCreatePriority string

// TodoUpdate defines model for TodoUpdate.
type TodoUpdate struct {
	// Completed Whether the todo is completed.
	Completed *bool `json:"completed,omitempty"`

	// Description Detailed description of the todo.
	Description *string `json:"description,omitempty"`

	// DueDate The due date for the todo.
	DueDate *time.Time `json:"due_date,omitempty"`

	// Priority Priority level of the todo.
	Priority *TodoUpdatePriority `json:"priority,omitempty"`

	// Title The title of the todo.
	Title *string `json:"title,omitempty"`
}

// TodoUpdatePriority Priority level of the todo.
type TodoUpdatePriority string

// GetTodosParams defines parameters for GetTodos.
type GetTodosParams struct {
	// Completed Filter todos by completion status
	Completed *bool `form:"completed,omitempty" json:"completed,omitempty"`

	// Priority Filter todos by priority level
	Priority *GetTodosParamsPriority `form:"priority,omitempty" json:"priority,omitempty"`
}

// GetTodosParamsPriority defines parameters for GetTodos.
type GetTodosParamsPriority string

// PostTodosJSONRequestBody defines body for PostTodos for application/json ContentType.
type PostTodosJSONRequestBody = TodoCreate

// PutTodosIdJSONRequestBody defines body for PutTodosId for application/json ContentType.
type PutTodosIdJSONRequestBody = TodoUpdate
